#!/usr/bin/env python3
"""Create a shadow-montage tilt series from 4D-STEM ARINA HDF5 files.
Citation: https://doi.org/10.1093/mam/ozaf126
license: GPL-v3
installation: pip install numpy scipy h5py
Usage:
    python shadow_montage_tiltseries.py metadata.json
    python shadow_montage_tiltseries.py metadata.json --Ns 2.5

The script follows the source MATLAB code, https://github.com/Pr4Et/Supplementaries/blob/main/Shadow_Montage/ShadowMontage_tiltseries_ver2.m.
New feature:  the input parameters are extracted from the json metadata file generated by https://github.com/elbaum-lab/Session-JSON
"""
from __future__ import annotations

import argparse
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path

import h5py
import mrcfile
import numpy as np
from scipy.ndimage import zoom

# MATLAB options that are not represented in the metadata JSON.
REQUIRED_UPSCALING = 2.0     #Rendedred upscaling regardless of conditions
APPLY_CTF_CORRECTION = True
MARGIN = 0.0625


@dataclass(frozen=True)
class Settings:
    json_path: Path
    folder: Path
    master_name: str
    scan_source: str
    scan_indices: list[int]
    tilt_angles_deg: list[float]
    Nx: int
    Ny: int
    defocus_um: float
    convergence_angle_mrad: float
    step_size_nm: float
    energy_keV: float
    camera_size: int
    dectris_arina: bool
    old_arina: bool
    left_to_column: bool


def selected(node: dict, context: str) -> str:
    try:
        return str(node["selected"])
    except (KeyError, TypeError) as exc:
        raise ValueError(f"Missing {context}.selected") from exc


def load_json(path: Path) -> dict:
    try:
        with path.open("r", encoding="utf-8-sig") as f:
            return json.load(f)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid JSON in {path} at line {exc.lineno}, column {exc.colno}: {exc.msg}"
        ) from exc


def get_raster_parameters(scan: dict, label: str) -> tuple[int, int, float]:
    mode = selected(scan["scan_mode"], f"{label}.scan_mode")
    mode_data = scan["scan_mode"].get("data", {}).get(mode)
    if not isinstance(mode_data, dict):
        raise ValueError(f"No scan parameters for {label} scan mode {mode!r}")
    try:
        return int(mode_data["Nx"]), int(mode_data["Ny"]), float(mode_data["step_size_nm"])
    except KeyError as exc:
        raise ValueError(f"Missing {label}.scan_mode.data.{mode}.{exc.args[0]}") from exc


def find_arina(scan: dict, label: str) -> tuple[bool, dict]:
    detectors = scan.get("detectors", {})
    for detector_name, detector in detectors.items():
        if isinstance(detector, dict) and detector.get("selected") == "ARINA":
            arina = detector.get("data", {}).get("ARINA", {})
            if not isinstance(arina, dict):
                raise ValueError(f"Malformed ARINA settings in {label}.{detector_name}")
            return True, arina
    return False, {}


def parse_settings(json_path: Path) -> Settings:
    root = load_json(json_path)
    microscope_mode = root.get("microscope_mode", {})
    if selected(microscope_mode, "microscope_mode") != "4D-STEM":
        raise ValueError("The metadata must have microscope_mode.selected == '4D-STEM'.")

    stem = microscope_mode.get("data", {}).get("4D-STEM")
    if not isinstance(stem, dict):
        raise ValueError("Missing microscope_mode.data['4D-STEM'] settings.")

    main = stem.get("main_scan")
    if not isinstance(main, dict):
        raise ValueError("Missing 4D-STEM main_scan.")
    try:
        main_defocus = float(main["beam"]["defocus_um"])
    except KeyError as exc:
        raise ValueError("Missing main_scan.beam.defocus_um") from exc

    if main_defocus != 0.0:
        scan = main
        source = "main_scan"
        first_scan_index = 0
    else:
        additional = stem.get("additional_scan")
        if not isinstance(additional, dict) or not additional:
            raise ValueError("main_scan defocus is 0, but additional_scan is missing or empty.")
        # JSON object keys are strings. Select the numerically first additional scan.
        numeric_keys = sorted((int(k), k) for k in additional if str(k).isdigit())
        if not numeric_keys:
            raise ValueError("additional_scan contains no numeric scan key.")
        additional_number, additional_key = numeric_keys[0]
        scan = additional[additional_key]
        source = f"additional_scan[{additional_key}]"
        first_scan_index = additional_number

    Nx, Ny, step_size_nm = get_raster_parameters(scan, source)
    beam = scan.get("beam", {})
    try:
        defocus_um = float(beam["defocus_um"])
        convergence_angle_mrad = float(beam["convergence_angle_mrad"])
        energy_keV = float(beam["energy_kv"])
    except KeyError as exc:
        raise ValueError(f"Missing {source}.beam.{exc.args[0]}") from exc
    if defocus_um == 0.0:
        raise ValueError(f"Selected {source} also has zero defocus; Ns cannot be estimated unless --Ns is given.")

    is_arina, arina = find_arina(scan, source)
    if not is_arina:
        raise ValueError(f"No detector selected as ARINA in {source}.")
    camera_selection = selected(arina.get("ARINA_camera_size", {}), "ARINA_camera_size")
    camera_size = 96 if camera_selection == "96x96" else 192
    arina_type = selected(arina.get("ARINA_type", {}), "ARINA_type")
    if arina_type not in {"commercial", "prototype"}:
        raise ValueError("ARINA_type.selected must be 'commercial' or 'prototype'.")
    position = selected(arina.get("ARINA_position", {}), "ARINA_position")

    angles = root.get("tilt_angles_deg")
    if not isinstance(angles, list) or not angles:
        raise ValueError("tilt_angles_deg must be a non-empty list.")
    repetition = int(root.get("angle_repetition_factor", 1))
    if repetition < 1:
        raise ValueError("angle_repetition_factor must be >= 1.")
    # Main data use s0,sR,s2R,...; first additional data use s1,s(1+R),...
    scan_indices = list(range(first_scan_index, len(angles), repetition))
    selected_angles = [float(angles[i]) for i in scan_indices]

    folder = Path(str(root["folder_name"])).expanduser()
    master_name = str(root["master_name"])
    if not master_name:
        raise ValueError("master_name is empty.")

    return Settings(
        json_path=json_path, folder=folder, master_name=master_name,
        scan_source=source, scan_indices=scan_indices,
        tilt_angles_deg=selected_angles, Nx=Nx, Ny=Ny,
        defocus_um=defocus_um, convergence_angle_mrad=convergence_angle_mrad,
        step_size_nm=step_size_nm, energy_keV=energy_keV,
        camera_size=camera_size, dectris_arina=True,
        old_arina=(arina_type == "prototype"),
        left_to_column=(position == "left_to_column"),
    )


def _process_dataset_legacy(dset, start_index: int, array: np.ndarray) -> int:
    image_index = start_index
    for i in range(dset.shape[0]):
        array[image_index] = dset[i].astype(array.dtype, copy=False)
        image_index += 1
    return image_index


def load_legacy_h5_to_mat(h5_path: Path, nx_hint=None, ny_hint=None):
    """Loader copied from pidpc_pipeline.py; returns (H,W,T) in its MATLAB scan order."""
    with h5py.File(h5_path, "r") as f:
        entry = f["entry"]
        if isinstance(entry.get("data"), h5py.Dataset):
            dset = entry["data"]
            nimages, H, W = dset.shape
            array = np.empty((nimages, H, W), dtype=dset.dtype)
            _process_dataset_legacy(dset, 0, array)
        else:
            grp = entry["data"]
            datasets = [grp[name] for name in grp if isinstance(grp[name], h5py.Dataset)]
            if not datasets:
                raise ValueError(f"No datasets found under /entry/data in {h5_path}")
            nimages = sum(d.shape[0] for d in datasets)
            H, W, dtype = datasets[0].shape[1], datasets[0].shape[2], datasets[0].dtype
            array = np.empty((nimages, H, W), dtype=dtype)
            image_index = 0
            for dset in datasets:
                image_index = _process_dataset_legacy(dset, image_index, array)
        if array.dtype == np.uint32:
            print("Dataset is uint32; converting to uint16")
            array = array.astype(np.uint16, copy=False)
        if nx_hint and ny_hint and nx_hint * ny_hint == array.shape[0]:
            Nx, Ny = int(nx_hint), int(ny_hint)
        else:
            Nx = int(math.sqrt(array.shape[0]))
            Ny = int(array.shape[0] / Nx)
        mat = np.transpose(array.astype(np.float32, copy=False), (1, 2, 0))
        if mat.shape[2] != Nx * Ny:
            raise ValueError(f"Frame count {mat.shape[2]} != Nx*Ny {Nx*Ny}")
        perm = []
        for y_desc in range(Ny - 1, -1, -1):
            y_rm = (Ny - 1) - y_desc
            for x in range(Nx):
                perm.append(y_rm * Nx + x)
        mat = mat[:, :, np.asarray(perm, dtype=int)]
    return mat, Nx, Ny


def load_matlab_oriented(h5_path: Path, Nx: int, Ny: int) -> np.ndarray:
    mat, loaded_Nx, loaded_Ny = load_legacy_h5_to_mat(h5_path, nx_hint=Nx, ny_hint=Ny)
    if (loaded_Nx, loaded_Ny) != (Nx, Ny):
        raise ValueError(f"Loaded scan size {(loaded_Nx, loaded_Ny)} != JSON {(Nx, Ny)}")
    # Required one-time detector-plane swap. Keep the MATLAB array X/Y convention.
    return np.transpose(mat, (1, 0, 2))


def direction_parameters(s: Settings) -> tuple[int, float]:
    underfocus = s.defocus_um < 0.0
    if not s.old_arina:  # commercial ARINA
        if s.left_to_column:
            case = 4 if underfocus else 1
            defocus_sign = -1.0 if case == 4 else 1.0
        else:
            case = 1 if underfocus else 4
            defocus_sign = 1.0 if case == 4 else -1.0
    else:  # prototype ARINA
        if s.left_to_column:
            case = 2 if underfocus else 3
            defocus_sign = 1.0 if case == 3 else -1.0
        else:
            case = 3 if underfocus else 2
            defocus_sign = 1.0 if case == 2 else -1.0
    return case, defocus_sign


def probe_properties(mat: np.ndarray, camera_size: int) -> tuple[float, np.ndarray]:
    probe = np.zeros((camera_size, camera_size), dtype=np.float64)
    for ind in range(0, mat.shape[2], 10):
        im = np.nan_to_num(mat[:, :, ind], nan=0.0, posinf=0.0, neginf=0.0)
        im = np.where(im > 60000, 0, im)
        probe += im
    midv = 0.5 * (float(probe.max()) + float(probe.min()))
    mask = probe > midv
    diameter = 2.0 * math.sqrt(float(mask.sum()) / math.pi)
    return diameter, probe


def matlab_round_positive(x: float) -> int:
    return int(math.floor(x + 0.5))


def bilinear_resize(image: np.ndarray, shape: tuple[int, int]) -> np.ndarray:
    factors = (shape[0] / image.shape[0], shape[1] / image.shape[1])
    return zoom(image, factors, order=1, mode="nearest", prefilter=False)


def process_one(mat: np.ndarray, s: Settings, Ns: float, bf_diameter: float,
                case: int, defocus_sign: float, output_shape: tuple[int, int]) -> np.ndarray:
    camera = s.camera_size
    alpha_rad = s.convergence_angle_mrad / 1000.0
    canvas_x = matlab_round_positive(2 * camera + abs(Ns) * s.Nx)
    canvas_y = matlab_round_positive(2 * camera + abs(Ns) * s.Ny)
    margin_x = int(math.floor(MARGIN * canvas_x))
    margin_y = int(math.floor(MARGIN * canvas_y))

    probe = np.zeros((camera, camera), dtype=np.float64)
    for ind in range(0, mat.shape[2], 10):
        im = np.nan_to_num(mat[:, :, ind], nan=0.0, posinf=0.0, neginf=0.0)
        im = np.where(im > 60000, 0, im)
        probe += im
    mask = probe > 0.5 * (float(probe.max()) + float(probe.min()))
    weighted = probe * mask
    if weighted.sum() <= 0:
        raise ValueError("Could not determine the bright-field disk.")
    m_weight = weighted / weighted.sum()
    gv = np.arange(1, camera + 1) - (1 + camera) / 2.0
    NqY, NqX = np.meshgrid(gv, gv, indexing="xy")
    Xd0 = float((NqX[mask] * m_weight[mask]).sum())
    Yd0 = float((NqY[mask] * m_weight[mask]).sum())
    mask_keep = np.sqrt((NqX - Xd0) ** 2 + (NqY - Yd0) ** 2) <= (0.5 * bf_diameter - 2)

    xshift_dx = -Ns if case > 2 else Ns
    yshift_dy = Ns if case in (1, 3) else -Ns
    x0 = int(math.floor((1 + canvas_x) / 2.0)) - 1  # MATLAB index -> Python index
    y0 = int(math.floor((1 + canvas_y) / 2.0)) - 1
    grand_tile = np.zeros((canvas_x, canvas_y), dtype=np.float64)
    grand_count = np.zeros((canvas_x, canvas_y), dtype=np.uint32)

    frames = min(mat.shape[2], s.Nx * s.Ny)
    half_lo = camera // 2 - 1
    half_hi = camera // 2
    for ind0 in range(frames):
        # Exact source MATLAB convention: X changes fastest, Y increases by scan row.
        Xp = 1 + (ind0 % s.Nx)
        Yp = 1 + (ind0 // s.Nx)
        im = np.nan_to_num(mat[:, :, ind0], nan=0.0, posinf=0.0, neginf=0.0)
        im = np.where(im > 60000, 0, im) * mask_keep
        HR_Xc = matlab_round_positive(x0 + 1 + (Xp - s.Nx / 2.0) * xshift_dx) - 1
        HR_Yc = matlab_round_positive(y0 + 1 + (Yp - s.Ny / 2.0) * yshift_dy) - 1
        xs, xe = HR_Xc - half_lo, HR_Xc + half_hi + 1
        ys, ye = HR_Yc - half_lo, HR_Yc + half_hi + 1
        if xs < 0 or ys < 0 or xe > canvas_x or ye > canvas_y:
            continue
        grand_tile[xs:xe, ys:ye] += im
        grand_count[xs:xe, ys:ye] += mask_keep.astype(np.uint32)

    result = grand_tile / np.maximum(grand_count, 1)
    tile_image = result[::-1, :]

    if APPLY_CTF_CORRECTION:
        imageN = tile_image.shape[0]
        gv = np.arange(1, imageN + 1) - (1 + imageN) / 2.0
        qYr, qXr = np.meshgrid(gv, gv, indexing="xy")
        d_nm = s.step_size_nm
        qY_CTF = qYr / (imageN * d_nm / Ns)
        qX_CTF = qXr / (imageN * d_nm / Ns)
        q2 = qX_CTF ** 2 + qY_CTF ** 2
        q2_bf = (bf_diameter / imageN) ** 2
        calc_defocus_nm = bf_diameter * s.step_size_nm / (Ns * 2 * alpha_rad)
        wavelength_nm = 1.2398 / math.sqrt(s.energy_keV * (2 * 511 + s.energy_keV))
        ctf = np.sin(-defocus_sign * math.pi * calc_defocus_nm * wavelength_nm * q2)
        inv = np.where(ctf >= 0, 1.0, -1.0)
        if defocus_sign > 0:
            modulation = -np.cos((math.pi / 2.0) * (q2 / q2_bf))
            modulation[q2 > 2 * q2_bf] = 1.0
            inv *= modulation
        tile_image = np.real(np.fft.ifft2(np.fft.ifftshift(np.fft.fftshift(np.fft.fft2(tile_image)) * inv)))

    cropped = tile_image[margin_x:canvas_x - margin_x, margin_y:canvas_y - margin_y]
    return bilinear_resize(cropped, output_shape).astype(np.float32)


def make_output_path(s: Settings) -> Path:
    return s.folder / f"{s.master_name}_{s.scan_source.replace('[', '_').replace(']', '')}_Tiltview.mrc"


def run(json_path: Path, Ns_override: float | None) -> Path:
    s = parse_settings(json_path)
    paths = [s.folder / f"{s.master_name}_s{i}_master.h5" for i in s.scan_indices]
    existing_first = next((p for p in paths if p.is_file()), None)
    if existing_first is None:
        raise FileNotFoundError("No matching HDF5 file was found. First candidates:\n  " + "\n  ".join(map(str, paths[:5])))

    first_mat = load_matlab_oriented(existing_first, s.Nx, s.Ny)
    if first_mat.shape[:2] != (s.camera_size, s.camera_size):
        raise ValueError(f"Detector data shape {first_mat.shape[:2]} does not match JSON camera size {s.camera_size}.")
    bf_diameter, _ = probe_properties(first_mat, s.camera_size)
    if Ns_override is not None:
        if Ns_override <= 0:
            raise ValueError("--Ns must be positive.")
        Ns = float(Ns_override)
    else:
        alpha_rad = s.convergence_angle_mrad / 1000.0
        Ns = bf_diameter * (s.step_size_nm * 0.001) / (2 * abs(s.defocus_um) * alpha_rad)
    if Ns <= 0 or not np.isfinite(Ns):
        raise ValueError(f"Invalid Ns value: {Ns}")

    case, defocus_sign = direction_parameters(s)
    canvas_x = matlab_round_positive(2 * s.camera_size + abs(Ns) * s.Nx)
    canvas_y = matlab_round_positive(2 * s.camera_size + abs(Ns) * s.Ny)
    crop_x = canvas_x - 2 * int(math.floor(MARGIN * canvas_x))
    crop_y = canvas_y - 2 * int(math.floor(MARGIN * canvas_y))
    output_shape = (
        matlab_round_positive(crop_x * REQUIRED_UPSCALING / Ns),
        matlab_round_positive(crop_y * REQUIRED_UPSCALING / Ns),
    )

    print(f"Metadata: {json_path}")
    print(f"Parameter source: {s.scan_source}")
    print(f"MATLAB-order Nx, Ny: {s.Nx}, {s.Ny}")
    print(f"Camera: {s.camera_size}x{s.camera_size}; ARINA: {'prototype' if s.old_arina else 'commercial'}")
    print(f"ARINA left_to_column: {s.left_to_column}; direction case: {case}")
    print(f"BF disk diameter: {bf_diameter:.4f} px; Ns: {Ns:.6g}")
    print(f"Output image shape in MATLAB X/Y order: {output_shape}")

    volume = np.zeros((len(paths), output_shape[0], output_shape[1]), dtype=np.float32)
    for out_i, (scan_i, angle, path) in enumerate(zip(s.scan_indices, s.tilt_angles_deg, paths)):
        print(f"[{out_i + 1}/{len(paths)}] s{scan_i}, angle={angle:g}: {path.name}")
        if not path.is_file():
            print("  Missing; writing a black tilt image.")
            continue
        try:
            mat = first_mat if path == existing_first else load_matlab_oriented(path, s.Nx, s.Ny)
            volume[out_i] = process_one(mat, s, Ns, bf_diameter, case, defocus_sign, output_shape)
        except Exception as exc:
            print(f"  Failed ({exc}); writing a black tilt image.")

    # MATLAB ends with tilt_cor = tilt(end:-1:1,:,:). MRC stores (Z,Y,X).
    # The per-image arrays retain MATLAB's first/second dimensions; transpose each image for MRC Y/X.
    volume = volume[:, ::-1, :]
    mrc_data = np.transpose(volume, (0, 2, 1)).astype(np.float32, copy=False)
    output = make_output_path(s)
    output.parent.mkdir(parents=True, exist_ok=True)
    with mrcfile.new(output, overwrite=True) as mrc:
        mrc.set_data(mrc_data)
        mrc.voxel_size = (s.step_size_nm * 10 / REQUIRED_UPSCALING,) * 3
        mrc.update_header_stats()
    print(f"Wrote: {output}")
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description="MATLAB-compatible ARINA shadow montage from metadata JSON")
    parser.add_argument("json_file", type=Path, help="Microscopy metadata JSON file")
    parser.add_argument("--Ns", type=float, default=None, help="Explicit synchronization step; otherwise estimate from defocus")
    args = parser.parse_args()
    run(args.json_file.resolve(), args.Ns)


if __name__ == "__main__":
    main()
